### ISSUE TITLE
App is crashing on deploying

### ISSUE THREAD

**Issue by sherlockia2** [AnimeKaizoku/ArchivsitsBot#9]
https://pasty.lus.pm/ICWlAr

Please refer logs

**Comment by HikaruHokkyokusei** [comment]
I don't know why it has crashed when you deployed, but I have updated the code so that inheritance is removed, hence no issue of abstract class, and new types of filters are implemented. Try using the new code.

**Comment by HikaruHokkyokusei** [comment]
Rebase with the final amended commit, and issue shall perish.
